### ISSUE TITLE
Piping output to file (or to `less`) doesn't display syntax highlighting

### ISSUE THREAD

**Issue by muhammad-abbady** [OmarTawfik/vscat#6]
Check these first few output lines from executing `vscode ./package.json | less -R`:
```
  1 │ {
  2 │ ··"name":·"vscat",
  3 │ ··"description":·"Bringing·VS·Code·syntax·highlighting·to·the·term…
  4 │ ··"version":·"0.0.0",
  5 │ ··"private":·false,
  6 │ ··"repository":·"https://github.com/OmarTawfik/vscat",
  7 │ ··"author":·"Omar·Tawfik·<15987992+OmarTawfik@users.noreply.github…
  8 │ ··"license":·"MIT",
  9 │ ··"main":·"out/src/index.js",
 10 │ ··"bin":·{
 11 │ ····"vscat":·"out/src/cli.js"
 12 │ ··},
 13 │ ··"scripts":·{
 14 │ ····"generate-metadata":·"ts-node-transpile-only·./scripts/metadat…
 15 │ ····"generate-readme":·"ts-node·./scripts/readme",
 16 │ ····"lint":·"jest·&&·prettier·.·--list-different·&&·tsc"
```

* Spaces are displayed as dots by default.
* Lines that are longer than a certain number of characters are truncated with an ellipses (sounds like a bug)
* Syntax highlighting doesn't show up with `less -R`.

Suggestions:
* An option to omit characters related to coloring and/or showing whitespaces.
* An option to force ANSI color escape sequences and OSC 8 hyperlink sequences, even if the output is piped.

**Comment by OmarTawfik** [comment]
Thanks for the suggestions:

> Spaces are displayed as dots by default. An option to omit characters related to coloring and/or showing whitespaces.

We can export an option/flag to disable whitespace presentation (spaces and tabs). I created #8 for that.

But can you expand on that you mean by characters related to coloring? you mean disable syntax highlighting? what is the usage scenario here?

> Lines that are longer than a certain number of characters are truncated with an ellipses (sounds like a bug)

This is expected behavior, since this allows better readability for large files in terminals. Happy to discuss if you see otherwise.

> Syntax highlighting doesn't show up with less -R.
> An option to force ANSI color escape sequences and OSC 8 hyperlink sequences, even if the output is piped.

You can do that if you set env `FORCE_COLOR=3`, as it forces color output, even if it going into a pipe.

**Comment by OmarTawfik** [comment]
@muhammad-abbady please let me know if the `FORCE_COLOR` option does not work for you. Please feel free to reactivate this issue if needed.
